### ISSUE TITLE
Contract address in docs is old? 

### ISSUE THREAD

**Issue by kariya2** [makerdao/pymaker#113]
docs have 
```
tub = Tub(web3=web3, address=Address('0xb7ae5ccabd002b5eebafe6a8fad5499394f67980'))
```
https://github.com/makerdao/sai
from here we can see: `export SAI_TUB=0x448a5065aebb8e423f0896e6c5d525c040f59af3`

**Comment by EdNoepel** [comment]
Indeed; TAP contract was wrong too.  Resolved in dff913768ce11c45f50094dc63d6b1f189f1db33; thank you for reporting.
