### ISSUE TITLE
Medianizer abi and object 

### ISSUE THREAD

**Issue by kariya2** [makerdao/pymaker#115]
Is this something that was left out intentionally, is there another place to access it? And if not are there plans to add it here?

**Comment by EdNoepel** [comment]
Do you intend to run an oracle, or were you looking to interact with it to retrieve a medianized price?

**Comment by kariya2** [comment]
just looking to interact with it and retrieve a price. My first rodeo with Dapps so looking to test the waters here :) 
Hopefully more than that one day though! 

If this isn't the right place to try to access this data from, please let me know if there's another resource to do this through

**Comment by kariya2** [comment]
Separately is it possible to access the historical s2s rate using this API or any other public endpoints?

**Comment by EdNoepel** [comment]
You need to be on a whitelist to read the price.  We’re in the processing of creating an Oracle Governance Framework which will need to be reviewed and ratified by MKR Governance. The framework will contain the application process to apply for the whitelist.

This API does not interact with the medianizer or provide current/historical pricing data.  I recommend joining us on https://chat.makerdao.com so we can better understand how to help you.
