### ISSUE TITLE
Jug.base should be a Ray, not a Wad

### ISSUE THREAD

**Issue by KentonPrescott** [makerdao/pymaker#171]
[The method](https://github.com/makerdao/pymaker/blob/master/pymaker/dss.py#L746) that queries `Jug.base` should return a Ray numeric type, not Wad. 
Old:
```
def base(self) -> Wad:
        return Wad(self._contract.functions.base().call())
```
New:
```
def base(self) -> Ray:
        return Ray(self._contract.functions.base().call())
```

**Comment by EdNoepel** [comment]
Sure; I'm validating that claim against [this unit test](https://github.com/makerdao/dss/blob/master/src/test/jug.t.sol#L175), since the contract itself isn't documented.

**Comment by KentonPrescott** [comment]
Whoops, I missed some proof 👍 . Thanks for adding a link.

For other readers, the way `base` and `ilks[ilk].duty` are [added](https://github.com/makerdao/dss/blob/master/src/jug.sol#L104) also suggests the units.

**Comment by EdNoepel** [comment]
Resolved by https://github.com/makerdao/pymaker/pull/172
