### ISSUE TITLE
Ability to take orders

### ISSUE THREAD

**Issue by livnev** [makerdao/pymaker#22]
Would be good for the keeper to have the ability to take an order that is priced the same or better than an outstanding order (or one about to be placed).

I guess this will be irrelevant with order matching.

**Comment by nmushegian** [comment]
order matching is not a long term solution, "taking" will mean interacting with one (possibly composite) LPC contract. "making" will mean placing a deposit/position with the LPC.

**Comment by nmushegian** [comment]
"simple bids" can be a primitive on the maker side but the LPC will compose them, doing whatever is necessary to have the taker side be O(1) cost function
