### ISSUE TITLE
Error installing requirements

### ISSUE THREAD

**Issue by leoplct** [makerdao/pymaker#60]
Already tried the command below the Known macOS issues. But 

`pip3 install -r requirements.txt`

> Requirement already satisfied: pytz==2017.3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r requirements.txt (line 1))
> Requirement already satisfied: web3==3.16.4 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r requirements.txt (line 2))
> Requirement already satisfied: eth-abi==0.5.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r requirements.txt (line 3))
> Requirement already satisfied: eth-utils==0.7.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r requirements.txt (line 4))
> Collecting eth-testrpc==1.3.0 (from -r requirements.txt (line 5))
>   Using cached https://files.pythonhosted.org/packages/4e/fd/a991e55d0dbb755a67118b90585130b27037ae969cd8ea75ff3f6035efc5/eth_testrpc-1.3.0-py3-none-any.whl
> Requirement already satisfied: rlp==0.6.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r requirements.txt (line 6))
> Requirement already satisfied: requests==2.18.4 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r requirements.txt (line 7))
> Requirement already satisfied: pysha3>=0.3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from web3==3.16.4->-r requirements.txt (line 2))
> Requirement already satisfied: toolz>=0.8.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from web3==3.16.4->-r requirements.txt (line 2))
> Requirement already satisfied: pylru>=1.0.9 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from web3==3.16.4->-r requirements.txt (line 2))
> Requirement already satisfied: cytoolz>=0.8.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from web3==3.16.4->-r requirements.txt (line 2))
> Requirement already satisfied: eth-keyfile>=0.4.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from web3==3.16.4->-r requirements.txt (line 2))
> Requirement already satisfied: eth-tester~=0.1.0b2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from web3==3.16.4->-r requirements.txt (line 2))
> Requirement already satisfied: eth-keys>=0.1.0-beta.3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from web3==3.16.4->-r requirements.txt (line 2))
> Collecting ethereum<2.0.0,>=1.6.1 (from eth-testrpc==1.3.0->-r requirements.txt (line 5))
>   Using cached https://files.pythonhosted.org/packages/8d/d2/f20638de4c3ab6a28a64c079a7e20cede57491d872c6ce62b2e6839adfe6/ethereum-1.6.1.tar.gz
> Requirement already satisfied: json-rpc>=1.10.3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from eth-testrpc==1.3.0->-r requirements.txt (line 5))
> Requirement already satisfied: Werkzeug>=0.11.10 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from eth-testrpc==1.3.0->-r requirements.txt (line 5))
> Requirement already satisfied: click>=6.6 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from eth-testrpc==1.3.0->-r requirements.txt (line 5))
> Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests==2.18.4->-r requirements.txt (line 7))
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests==2.18.4->-r requirements.txt (line 7))
> Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests==2.18.4->-r requirements.txt (line 7))
> Requirement already satisfied: idna<2.7,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests==2.18.4->-r requirements.txt (line 7))
> Requirement already satisfied: pycryptodome<4.0.0,>=3.4.7 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from eth-keyfile>=0.4.0->web3==3.16.4->-r requirements.txt (line 2))
> Requirement already satisfied: semantic-version<3.0.0,>=2.6.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from eth-tester~=0.1.0b2->web3==3.16.4->-r requirements.txt (line 2))
> Requirement already satisfied: scrypt in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ethereum<2.0.0,>=1.6.1->eth-testrpc==1.3.0->-r requirements.txt (line 5))
> Collecting secp256k1 (from ethereum<2.0.0,>=1.6.1->eth-testrpc==1.3.0->-r requirements.txt (line 5))
>   Using cached https://files.pythonhosted.org/packages/52/62/d7bf3829e126e517e253d2e22a63511c54bbaac34d7ddea316cde040fc49/secp256k1-0.13.2.tar.gz
> Requirement already satisfied: pyethash in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ethereum<2.0.0,>=1.6.1->eth-testrpc==1.3.0->-r requirements.txt (line 5))
> Collecting bitcoin (from ethereum<2.0.0,>=1.6.1->eth-testrpc==1.3.0->-r requirements.txt (line 5))
>   Using cached https://files.pythonhosted.org/packages/12/88/c9390638d5b2713d38ccea46c93e8ec084f052a15a94f9b1d4c66baabd24/bitcoin-1.1.42.tar.gz
> Requirement already satisfied: repoze.lru in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ethereum<2.0.0,>=1.6.1->eth-testrpc==1.3.0->-r requirements.txt (line 5))
> Requirement already satisfied: PyYAML in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ethereum<2.0.0,>=1.6.1->eth-testrpc==1.3.0->-r requirements.txt (line 5))
> Requirement already satisfied: pbkdf2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ethereum<2.0.0,>=1.6.1->eth-testrpc==1.3.0->-r requirements.txt (line 5))
> Requirement already satisfied: cffi>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from secp256k1->ethereum<2.0.0,>=1.6.1->eth-testrpc==1.3.0->-r requirements.txt (line 5))
> Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from cffi>=1.3.0->secp256k1->ethereum<2.0.0,>=1.6.1->eth-testrpc==1.3.0->-r requirements.txt (line 5))
> Installing collected packages: secp256k1, bitcoin, ethereum, eth-testrpc
>   Running setup.py install for secp256k1 ... error
>     Complete output from command /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/1h/54vqnr6s1x1185qdfjtl02nc0000gn/T/pip-build-iwrj3vpi/secp256k1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/1h/54vqnr6s1x1185qdfjtl02nc0000gn/T/pip-3g5ekn_w-record/install-record.txt --single-version-externally-managed --compile:
>     0.29.2
>     Using bundled libsecp256k1
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.macosx-10.6-intel-3.6
>     creating build/lib.macosx-10.6-intel-3.6/secp256k1
>     copying secp256k1/__init__.py -> build/lib.macosx-10.6-intel-3.6/secp256k1
>     copying secp256k1/__main__.py -> build/lib.macosx-10.6-intel-3.6/secp256k1
>     running build_clib
>     /private/var/folders/1h/54vqnr6s1x1185qdfjtl02nc0000gn/T/pip-build-iwrj3vpi/secp256k1/libsecp256k1/autogen.sh: line 3: autoreconf: command not found
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/1h/54vqnr6s1x1185qdfjtl02nc0000gn/T/pip-build-iwrj3vpi/secp256k1/setup.py", line 295, in <module>
>         "Topic :: Security :: Cryptography"
>       File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
>         return distutils.core.setup(**attrs)
>       File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
>         dist.run_commands()
>       File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
>         self.run_command(cmd)
>       File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
>         return orig.install.run(self)
>       File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 545, in run
>         self.run_command('build')
>       File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
>         self.run_command(cmd_name)
>       File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/private/var/folders/1h/54vqnr6s1x1185qdfjtl02nc0000gn/T/pip-build-iwrj3vpi/secp256k1/setup.py", line 165, in run
>         cwd=absolute("libsecp256k1"),
>       File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
>         raise CalledProcessError(retcode, cmd)
>     subprocess.CalledProcessError: Command '['/private/var/folders/1h/54vqnr6s1x1185qdfjtl02nc0000gn/T/pip-build-iwrj3vpi/secp256k1/libsecp256k1/autogen.sh']' returned non-zero exit status 127.
>     
>     ----------------------------------------
> Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/1h/54vqnr6s1x1185qdfjtl02nc0000gn/T/pip-build-iwrj3vpi/secp256k1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/1h/54vqnr6s1x1185qdfjtl02nc0000gn/T/pip-3g5ekn_w-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/1h/54vqnr6s1x1185qdfjtl02nc0000gn/T/pip-build-iwrj3vpi/secp256k1/
> You are using pip version 9.0.3, however version 10.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by reverendus** [comment]
Looks like some other dependency of `secp256k1 ` is missing:

```'['/private/var/folders/1h/54vqnr6s1x1185qdfjtl02nc0000gn/T/pip-build-iwrj3vpi/secp256k1/libsecp256k1/autogen.sh']' returned non-zero exit status 127.```

It's difficult to tell which one it is though. I'd recommend trying again and straight away after it fails entering that temporary directory and running `./autogen.sh` manually. You should be able to tell what's actually missing by the output of it.

**Comment by finackieee** [comment]
I had the same issue, try install these dependencies, specifically **libsecp256k1-dev**
`apt-get install build-essential automake libtool pkg-config libffi-dev python-dev python-pip libsecp256k1-dev`

**Comment by finackieee** [comment]
I had the same issue, try installing these dependencies, specifically **libsecp256k1-dev**
`apt-get install build-essential automake libtool pkg-config libffi-dev python-dev python-pip libsecp256k1-dev`

**Comment by reverendus** [comment]
Closing as this is already mentioned in `README.md`.
